# Generated by Django 3.2.9 on 2021-11-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeperName', models.CharField(max_length=50)),
                ('funName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fantasyteam')),
            ],
        ),
    ]
