# Generated by Django 3.2.9 on 2021-11-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nflTeam', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='currentProj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='matchup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='sleeperId',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='spreadLoss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='spreadWin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='tie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='currentProj',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='dst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='k',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='qb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='rb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='sleeperId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='te',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='wr',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProjPoints',
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.fantasyteam'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.player'),
        ),
    ]
