# Generated by Django 3.2.9 on 2021-11-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211123_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='player',
            name='k',
        ),
        migrations.RemoveField(
            model_name='player',
            name='qb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='te',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wr',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentTeam',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='main.fantasyteam'),
        ),
    ]
