# Generated by Django 3.2.9 on 2021-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fantasyteam_rosterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nflTeam',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
