# Generated by Django 3.2.9 on 2021-11-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_player_nflteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhistory',
            name='opponent',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, related_name='opponent', to='main.fantasyteam'),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='proj',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mainTeam', to='main.fantasyteam'),
        ),
    ]
