# Generated by Django 3.2.9 on 2021-11-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211126_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overUnder', models.FloatField(null=True)),
                ('spreadT1', models.FloatField(null=True)),
                ('team1Ml', models.FloatField(null=True)),
                ('team2Ml', models.FloatField(null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='main.fantasyteam')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team2', to='main.fantasyteam')),
            ],
        ),
    ]
