# Generated by Django 3.2.9 on 2021-11-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='matchupId',
            field=models.IntegerField(default=0),
        ),
    ]
