# Generated by Django 3.2.9 on 2021-11-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_matchup_matchupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='spreadT2',
            field=models.FloatField(null=True),
        ),
    ]
