# Generated by Django 3.2.9 on 2021-12-06 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20211206_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='wager',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bets',
            name='wagerType',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
