# Generated by Django 3.2.9 on 2021-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211206_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='sleeperId',
            field=models.IntegerField(default=0),
        ),
    ]
