# Generated by Django 3.2.9 on 2021-12-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_proxy_sleeperid'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='weeklyBalance',
            field=models.FloatField(default=0),
        ),
    ]
