# Generated by Django 3.2.9 on 2021-12-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_proxy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='starter',
            field=models.BooleanField(default=False),
        ),
    ]
