# Generated by Django 3.2.9 on 2021-12-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_player_starter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLineUpdate', models.DateTimeField()),
                ('lastMatchupUpdate', models.DateTimeField()),
            ],
        ),
    ]
