# Generated by Django 3.2.9 on 2021-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211207_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchup',
            name='matchupId',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
