# Generated by Django 3.2.9 on 2021-12-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_matchup_matchupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='matchup',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
